# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fridgemonitor_parts\fridgemonitor.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_FridgeMonitorWindow(object):
    def setupUi(self, FridgeMonitorWindow):
        FridgeMonitorWindow.setObjectName("FridgeMonitorWindow")
        FridgeMonitorWindow.resize(1346, 676)
        self.centralwidget = QtWidgets.QWidget(FridgeMonitorWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.plot_holder = QtWidgets.QWidget(self.centralwidget)
        self.plot_holder.setObjectName("plot_holder")
        self.horizontalLayout_10.addWidget(self.plot_holder)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.startStopButton = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startStopButton.sizePolicy().hasHeightForWidth())
        self.startStopButton.setSizePolicy(sizePolicy)
        self.startStopButton.setMaximumSize(QtCore.QSize(150, 16777215))
        self.startStopButton.setObjectName("startStopButton")
        self.verticalLayout.addWidget(self.startStopButton)
        self.alarmCheckBox = QtWidgets.QCheckBox(self.frame)
        self.alarmCheckBox.setObjectName("alarmCheckBox")
        self.verticalLayout.addWidget(self.alarmCheckBox)
        self.checkBox_latest = QtWidgets.QCheckBox(self.frame)
        self.checkBox_latest.setChecked(True)
        self.checkBox_latest.setObjectName("checkBox_latest")
        self.verticalLayout.addWidget(self.checkBox_latest)
        self.checkBox_lock_x = QtWidgets.QCheckBox(self.frame)
        self.checkBox_lock_x.setChecked(True)
        self.checkBox_lock_x.setObjectName("checkBox_lock_x")
        self.verticalLayout.addWidget(self.checkBox_lock_x)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.autoScaleButton = QtWidgets.QPushButton(self.frame)
        self.autoScaleButton.setObjectName("autoScaleButton")
        self.horizontalLayout_6.addWidget(self.autoScaleButton)
        self.manualScaleButton = QtWidgets.QPushButton(self.frame)
        self.manualScaleButton.setObjectName("manualScaleButton")
        self.horizontalLayout_6.addWidget(self.manualScaleButton)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.radioButton_Man = QtWidgets.QRadioButton(self.frame)
        self.radioButton_Man.setObjectName("radioButton_Man")
        self.verticalLayout.addWidget(self.radioButton_Man)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.htrOutputLabel = QtWidgets.QLabel(self.frame)
        self.htrOutputLabel.setObjectName("htrOutputLabel")
        self.horizontalLayout_3.addWidget(self.htrOutputLabel)
        self.htrOutputLineEdit = QtWidgets.QLineEdit(self.frame)
        self.htrOutputLineEdit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.htrOutputLineEdit.setObjectName("htrOutputLineEdit")
        self.horizontalLayout_3.addWidget(self.htrOutputLineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.htrRangeLabel = QtWidgets.QLabel(self.frame)
        self.htrRangeLabel.setObjectName("htrRangeLabel")
        self.horizontalLayout_2.addWidget(self.htrRangeLabel)
        self.htrRangeComboBox = QtWidgets.QComboBox(self.frame)
        self.htrRangeComboBox.setObjectName("htrRangeComboBox")
        self.htrRangeComboBox.addItem("")
        self.htrRangeComboBox.addItem("")
        self.htrRangeComboBox.addItem("")
        self.htrRangeComboBox.addItem("")
        self.htrRangeComboBox.addItem("")
        self.htrRangeComboBox.addItem("")
        self.htrRangeComboBox.addItem("")
        self.htrRangeComboBox.addItem("")
        self.htrRangeComboBox.addItem("")
        self.horizontalLayout_2.addWidget(self.htrRangeComboBox)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.cancelButton = QtWidgets.QPushButton(self.frame)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout_5.addWidget(self.cancelButton)
        self.updateButton = QtWidgets.QPushButton(self.frame)
        self.updateButton.setObjectName("updateButton")
        self.horizontalLayout_5.addWidget(self.updateButton)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.radioButton_PID = QtWidgets.QRadioButton(self.frame)
        self.radioButton_PID.setObjectName("radioButton_PID")
        self.verticalLayout.addWidget(self.radioButton_PID)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.htrOutputLabel_2 = QtWidgets.QLabel(self.frame)
        self.htrOutputLabel_2.setObjectName("htrOutputLabel_2")
        self.horizontalLayout_4.addWidget(self.htrOutputLabel_2)
        self.PIDLineEdit = QtWidgets.QLineEdit(self.frame)
        self.PIDLineEdit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.PIDLineEdit.setObjectName("PIDLineEdit")
        self.horizontalLayout_4.addWidget(self.PIDLineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.fileNameLabel = QtWidgets.QLabel(self.frame)
        self.fileNameLabel.setObjectName("fileNameLabel")
        self.horizontalLayout.addWidget(self.fileNameLabel)
        self.proportionalLineEdit = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.proportionalLineEdit.sizePolicy().hasHeightForWidth())
        self.proportionalLineEdit.setSizePolicy(sizePolicy)
        self.proportionalLineEdit.setObjectName("proportionalLineEdit")
        self.horizontalLayout.addWidget(self.proportionalLineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.fileNameLabel_2 = QtWidgets.QLabel(self.frame)
        self.fileNameLabel_2.setObjectName("fileNameLabel_2")
        self.horizontalLayout_7.addWidget(self.fileNameLabel_2)
        self.integralLineEdit = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.integralLineEdit.sizePolicy().hasHeightForWidth())
        self.integralLineEdit.setSizePolicy(sizePolicy)
        self.integralLineEdit.setObjectName("integralLineEdit")
        self.horizontalLayout_7.addWidget(self.integralLineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.fileNameLabel_4 = QtWidgets.QLabel(self.frame)
        self.fileNameLabel_4.setObjectName("fileNameLabel_4")
        self.horizontalLayout_9.addWidget(self.fileNameLabel_4)
        self.dampingLineEdit = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dampingLineEdit.sizePolicy().hasHeightForWidth())
        self.dampingLineEdit.setSizePolicy(sizePolicy)
        self.dampingLineEdit.setObjectName("dampingLineEdit")
        self.horizontalLayout_9.addWidget(self.dampingLineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.updatePIDButton = QtWidgets.QPushButton(self.frame)
        self.updatePIDButton.setObjectName("updatePIDButton")
        self.verticalLayout.addWidget(self.updatePIDButton)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.fileNameLabel_3 = QtWidgets.QLabel(self.frame)
        self.fileNameLabel_3.setObjectName("fileNameLabel_3")
        self.horizontalLayout_8.addWidget(self.fileNameLabel_3)
        self.equationLineEdit = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.equationLineEdit.sizePolicy().hasHeightForWidth())
        self.equationLineEdit.setSizePolicy(sizePolicy)
        self.equationLineEdit.setObjectName("equationLineEdit")
        self.horizontalLayout_8.addWidget(self.equationLineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        spacerItem = QtWidgets.QSpacerItem(20, 496, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_10.addWidget(self.frame)
        FridgeMonitorWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(FridgeMonitorWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1346, 21))
        self.menubar.setObjectName("menubar")
        FridgeMonitorWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(FridgeMonitorWindow)
        self.statusbar.setObjectName("statusbar")
        FridgeMonitorWindow.setStatusBar(self.statusbar)

        self.retranslateUi(FridgeMonitorWindow)
        QtCore.QMetaObject.connectSlotsByName(FridgeMonitorWindow)

    def retranslateUi(self, FridgeMonitorWindow):
        _translate = QtCore.QCoreApplication.translate
        FridgeMonitorWindow.setWindowTitle(_translate("FridgeMonitorWindow", "Thermometry"))
        self.startStopButton.setText(_translate("FridgeMonitorWindow", "Start"))
        self.alarmCheckBox.setText(_translate("FridgeMonitorWindow", "Send text messages"))
        self.checkBox_latest.setText(_translate("FridgeMonitorWindow", "Always show latest data"))
        self.checkBox_lock_x.setText(_translate("FridgeMonitorWindow", "Lock x axes together"))
        self.autoScaleButton.setText(_translate("FridgeMonitorWindow", "Auto scale all"))
        self.manualScaleButton.setText(_translate("FridgeMonitorWindow", "Manual scale all"))
        self.radioButton_Man.setText(_translate("FridgeMonitorWindow", "Manual Output"))
        self.htrOutputLabel.setText(_translate("FridgeMonitorWindow", "Heater output:"))
        self.htrRangeLabel.setText(_translate("FridgeMonitorWindow", "Heater Range:"))
        self.htrRangeComboBox.setItemText(0, _translate("FridgeMonitorWindow", "OFF"))
        self.htrRangeComboBox.setItemText(1, _translate("FridgeMonitorWindow", "31.6 uA"))
        self.htrRangeComboBox.setItemText(2, _translate("FridgeMonitorWindow", "100 uA"))
        self.htrRangeComboBox.setItemText(3, _translate("FridgeMonitorWindow", "316 uA"))
        self.htrRangeComboBox.setItemText(4, _translate("FridgeMonitorWindow", "1.00 mA"))
        self.htrRangeComboBox.setItemText(5, _translate("FridgeMonitorWindow", "3.16 mA"))
        self.htrRangeComboBox.setItemText(6, _translate("FridgeMonitorWindow", "10.0 mA"))
        self.htrRangeComboBox.setItemText(7, _translate("FridgeMonitorWindow", "31.6 mA"))
        self.htrRangeComboBox.setItemText(8, _translate("FridgeMonitorWindow", "100 mA"))
        self.cancelButton.setText(_translate("FridgeMonitorWindow", "Cancel"))
        self.updateButton.setText(_translate("FridgeMonitorWindow", "Update"))
        self.radioButton_PID.setText(_translate("FridgeMonitorWindow", "PID control"))
        self.htrOutputLabel_2.setText(_translate("FridgeMonitorWindow", "PID setpoint"))
        self.fileNameLabel.setText(_translate("FridgeMonitorWindow", "P value:"))
        self.proportionalLineEdit.setText(_translate("FridgeMonitorWindow", "1.5"))
        self.fileNameLabel_2.setText(_translate("FridgeMonitorWindow", "I value:"))
        self.integralLineEdit.setText(_translate("FridgeMonitorWindow", "0.05"))
        self.fileNameLabel_4.setText(_translate("FridgeMonitorWindow", "Damping:"))
        self.dampingLineEdit.setText(_translate("FridgeMonitorWindow", "0.05"))
        self.updatePIDButton.setText(_translate("FridgeMonitorWindow", "Update"))
        self.fileNameLabel_3.setText(_translate("FridgeMonitorWindow", "CMN:"))
        self.equationLineEdit.setText(_translate("FridgeMonitorWindow", "4.36894/(mH-2.93629)"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FridgeMonitorWindow = QtWidgets.QMainWindow()
    ui = Ui_FridgeMonitorWindow()
    ui.setupUi(FridgeMonitorWindow)
    FridgeMonitorWindow.show()
    sys.exit(app.exec_())

